export DEVICE_MONITOR_INTERVAL=60
export COMPLIANCE_MONITOR_INTERVAL=60
export CONFIGURATION_MONITOR_INTERVAL=3600
export HOST_MONITOR_INTERVAL=60
export SERVICE_MONITOR_INTERVAL=60
export DISCOVERY_INTERVAL=3600
cd ~/quokka
flask run --host=0.0.0.0
